package wizard

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestFromNonInteractiveDefaults(t *testing.T) {
	cfg := NonInteractiveConfig{
		ProjectName: "my-app",
		GroupID:     "com.example",
		Language:    "java",
		BuildType:   "maven",
		Packaging:   "jar",
	}

	result := FromNonInteractive(cfg)
	assert.Equal(t, "my-app", result.ProjectName)
	assert.Equal(t, "my-app", result.ArtifactID, "artifact should default to project name")
	assert.Equal(t, "com.example.myapp", result.PackageName, "package should derive from group+artifact")
	assert.Equal(t, "Generated by SpringCLI", result.Description, "description should have default")
	assert.Equal(t, "3.5.0", result.BootVersion, "boot version should have default")
	assert.Equal(t, "21", result.JavaVersion, "java version should have default")
}

func TestFromNonInteractiveExplicitValues(t *testing.T) {
	cfg := NonInteractiveConfig{
		ProjectName:    "shop-api",
		GroupID:        "com.acme",
		ArtifactID:     "shop-service",
		Description:    "Shop backend",
		Language:       "kotlin",
		BuildType:      "gradle-kotlin",
		BootVersion:    "3.3.0",
		JavaVersion:    "21",
		Packaging:      "jar",
		Dependencies:   []string{"web", "jpa", "security"},
		InitGit:        true,
		GenerateEnv:    false,
		GenerateDocker: true,
	}

	result := FromNonInteractive(cfg)
	assert.Equal(t, "shop-api", result.ProjectName)
	assert.Equal(t, "shop-service", result.ArtifactID)
	assert.Equal(t, "com.acme.shopservice", result.PackageName)
	assert.Equal(t, "Shop backend", result.Description)
	assert.Equal(t, "kotlin", result.Language)
	assert.Equal(t, "gradle-kotlin", result.BuildTool)
	assert.Equal(t, "3.3.0", result.BootVersion)
	assert.Len(t, result.Dependencies, 3)
	assert.True(t, result.InitGit)
	assert.False(t, result.GenerateEnv)
	assert.True(t, result.GenerateDocker)
}

func TestFilterSelectedDeps(t *testing.T) {
	allOptions := []string{
		"──── Web ────",
		"Spring Web — Build web apps",
		"Spring WebFlux — Reactive web",
		"──── Data ────",
		"Spring Data JPA — Persist data",
	}
	depIDs := []string{"", "web", "webflux", "", "jpa"}
	selected := []string{"Spring Web — Build web apps", "Spring Data JPA — Persist data"}

	result := filterSelectedDeps(selected, allOptions, depIDs)
	require.Len(t, result, 2)
	assert.Equal(t, "web", result[0])
	assert.Equal(t, "jpa", result[1])
}

func TestFilterSelectedDepsSkipsDividers(t *testing.T) {
	allOptions := []string{
		"──── Web ────",
		"Spring Web — Build web apps",
	}
	depIDs := []string{"", "web"}
	// Even if someone somehow selected the divider.
	selected := []string{"──── Web ────", "Spring Web — Build web apps"}

	result := filterSelectedDeps(selected, allOptions, depIDs)
	require.Len(t, result, 1)
	assert.Equal(t, "web", result[0])
}

func TestFilterSelectedDepsEmpty(t *testing.T) {
	result := filterSelectedDeps(nil, nil, nil)
	assert.Empty(t, result)
}

func TestMapBuildToolToType(t *testing.T) {
	assert.Equal(t, "maven", MapBuildToolToType("Maven"))
	assert.Equal(t, "gradle", MapBuildToolToType("Gradle (Groovy DSL)"))
	assert.Equal(t, "gradle-kotlin", MapBuildToolToType("Gradle (Kotlin DSL)"))
	assert.Equal(t, "maven", MapBuildToolToType("Unknown"))
}

func TestMapLanguageToAPI(t *testing.T) {
	assert.Equal(t, "java", MapLanguageToAPI("Java"))
	assert.Equal(t, "kotlin", MapLanguageToAPI("Kotlin"))
	assert.Equal(t, "groovy", MapLanguageToAPI("Groovy"))
	assert.Equal(t, "java", MapLanguageToAPI("Unknown"))
}

func TestCleanBootVersion(t *testing.T) {
	assert.Equal(t, "3.3.0", CleanBootVersion("3.3.0 (latest)"))
	assert.Equal(t, "3.2.3", CleanBootVersion("3.2.3"))
	assert.Equal(t, "3.1.10", CleanBootVersion("3.1.10"))
}

func TestBuildProjectInfoQuestions(t *testing.T) {
	questions := BuildProjectInfoQuestions("my-service")
	require.Len(t, questions, 5)
	assert.Equal(t, "projectName", questions[0].Name)
	assert.Equal(t, "groupID", questions[1].Name)
	assert.Equal(t, "artifactID", questions[2].Name)
	assert.Equal(t, "description", questions[3].Name)
	assert.Equal(t, "packageName", questions[4].Name)
}
