package project

// BuildType represents the type of build system used by a project.
type BuildType string

const (
	// BuildTypeMaven represents a Maven project (pom.xml).
	BuildTypeMaven BuildType = "maven"
	// BuildTypeGradleGroovy represents a Gradle Groovy project (build.gradle).
	BuildTypeGradleGroovy BuildType = "gradle"
	// BuildTypeGradleKotlin represents a Gradle Kotlin DSL project (build.gradle.kts).
	BuildTypeGradleKotlin BuildType = "gradle-kotlin"
	// BuildTypeUnknown means no recognizable build file was found.
	BuildTypeUnknown BuildType = "unknown"
)

// ProjectConfig holds the configuration for creating a new Spring Boot project.
type ProjectConfig struct {
	Name        string
	GroupID     string
	ArtifactID  string
	Description string
	Language    string
	BuildType   string
	BootVersion string
	JavaVersion string
	Packaging   string
	Dependencies []string
}

// DefaultProjectConfig returns a ProjectConfig with sensible defaults.
func DefaultProjectConfig(name string) ProjectConfig {
	artifactID := name
	return ProjectConfig{
		Name:        name,
		GroupID:     "com.example",
		ArtifactID:  artifactID,
		Description: "Generated by SpringCLI",
		Language:    "java",
		BuildType:   "maven",
		BootVersion: "3.2.3",
		JavaVersion: "17",
		Packaging:   "jar",
	}
}
