package cmd

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
	"github.com/springcli/springcli/internal/initializr"
)

var newCmd = &cobra.Command{
	Use:   "new <project-name>",
	Short: "Create a new Spring Boot project",
	Long: `Scaffold a new Spring Boot project by downloading from start.spring.io
and extracting it into the specified directory.`,
	Args: cobra.ExactArgs(1),
	RunE: runNew,
}

var (
	newGroup       string
	newArtifact    string
	newDescription string
	newLanguage    string
	newType        string
	newBoot        string
	newJava        string
	newPackaging   string
	newDeps        string
)

func init() {
	newCmd.Flags().StringVarP(&newGroup, "group", "g", "com.example", "Maven group ID")
	newCmd.Flags().StringVarP(&newArtifact, "artifact", "a", "", "Maven artifact ID (defaults to project name)")
	newCmd.Flags().StringVarP(&newDescription, "description", "d", "Generated by SpringCLI", "Project description")
	newCmd.Flags().StringVarP(&newLanguage, "language", "l", "java", "Language: java, kotlin, groovy")
	newCmd.Flags().StringVarP(&newType, "type", "t", "maven", "Build type: maven, gradle, gradle-kotlin")
	newCmd.Flags().StringVarP(&newBoot, "boot", "b", "3.2.3", "Spring Boot version")
	newCmd.Flags().StringVarP(&newJava, "java", "j", "17", "Java version: 17, 21")
	newCmd.Flags().StringVar(&newPackaging, "packaging", "jar", "Packaging: jar, war")
	newCmd.Flags().StringVar(&newDeps, "deps", "", "Comma-separated dependency IDs (e.g., web,jpa,security)")
}

func runNew(cmd *cobra.Command, args []string) error {
	projectName := args[0]

	if newArtifact == "" {
		newArtifact = projectName
	}

	// Check if target directory already exists.
	targetDir := filepath.Join(".", projectName)
	if _, err := os.Stat(targetDir); err == nil {
		return fmt.Errorf("directory '%s' already exists", projectName)
	}

	// Build package name from group + artifact (remove hyphens).
	packageName := newGroup + "." + strings.ReplaceAll(newArtifact, "-", "")

	// Parse dependencies.
	var deps []string
	if newDeps != "" {
		deps = strings.Split(newDeps, ",")
		for i := range deps {
			deps[i] = strings.TrimSpace(deps[i])
		}
	}

	// Display project summary.
	printer.Header("Creating Spring Boot Project")
	fmt.Println()
	printer.Step("Project name  : %s", projectName)
	printer.Step("Group ID      : %s", newGroup)
	printer.Step("Artifact ID   : %s", newArtifact)
	printer.Step("Build tool    : %s", newType)
	printer.Step("Language      : %s", newLanguage)
	printer.Step("Boot version  : %s", newBoot)
	printer.Step("Java version  : %s", newJava)
	printer.Step("Packaging     : %s", newPackaging)
	if len(deps) > 0 {
		printer.Step("Dependencies  : %s", strings.Join(deps, ", "))
	}
	fmt.Println()

	// Download the project.
	s := printer.StartSpinner("Downloading from start.spring.io...")
	client := initializr.NewClient()
	config := initializr.ProjectDownloadConfig{
		Type:         newType,
		Language:     newLanguage,
		BootVersion:  newBoot,
		BaseDir:      projectName,
		GroupID:      newGroup,
		ArtifactID:   newArtifact,
		Name:         projectName,
		Description:  newDescription,
		PackageName:  packageName,
		Packaging:    newPackaging,
		JavaVersion:  newJava,
		Dependencies: deps,
	}

	ctx := context.Background()
	if err := client.DownloadProject(ctx, config, "."); err != nil {
		printer.StopSpinner(s, "")
		return fmt.Errorf("downloading project: %w", err)
	}

	printer.StopSpinner(s, "Download complete!")
	fmt.Println()
	printer.Success("Project '%s' created successfully!", projectName)
	fmt.Println()

	// Print next steps.
	printer.Dim("  cd %s", projectName)
	switch newType {
	case "maven":
		printer.Dim("  ./mvnw spring-boot:run")
	case "gradle", "gradle-kotlin":
		printer.Dim("  ./gradlew bootRun")
	}
	fmt.Println()

	return nil
}
